### ISSUE TITLE
Sort directories before files

### ISSUE THREAD

**Issue by trapd00r** [bulletmark/edir#10]
I've tried my hands on fixing this myself but to no avail. :)

Can we get an option that lets us sort directories before files? 
Just like how `ls --group-directories-first` work, and how vidir does it.

**edir:**
![edir](https://i.imgur.com/5RxLCga.png)

**default vidir, no sort but directories still first:**
![vidir](https://i.imgur.com/F7Va5iF.png)

**vidir with -s flag (sort):**
![vidir](https://i.imgur.com/lK21eIH.png)

**Comment by bulletmark** [comment]
Generic `vidir` comes from Joey Hess moreutils and does not have any sorting options. Actually, the default order shown by that `vidir` is the same as the default order shown by `edir`. What `vidir` are you using?

**Comment by trapd00r** [comment]
Oh, my bad. I forgot that I've been using my own fork for many years, where I've been fixing and adding various things over the years.

https://github.com/trapd00r/vidir

I see that you already added the option, thank you for that!
