### ISSUE TITLE
[Enhancement] Add support for trash-d

### ISSUE THREAD

**Issue by fbearoff** [bulletmark/edir#11]
`edir` currently supports `trash-cli` whose syntax differs from `rm` making it not an ideal 1:1 replacement/alias. [trash-d](https://github.com/rushsteve1/trash-d) can be used as a drop-in replacement for `rm`. It would be great if `edir` could support trash-d.

Thanks!

**Comment by bulletmark** [comment]
Done with commit 41585a0665f939091433a739c452f50eea4abd3e and released as new version 2.11.

Thanks for the good suggestion.
