### ISSUE TITLE
Great work.

### ISSUE THREAD

**Issue by nkh** [bulletmark/edir#15]
There's a bunch of "better than the old applications" out there, most are much faster and most are much worse; you succeed putting a fine polish over vidir, clear documentation with the differences and credit where credit is due, bravo.

I have just replaced vidir with edir in my home grown file manager, took a few minutes (because I already had an edir function, otherwise 5 seconds). 

rename()        { tcpreview ; printf "%s\n" "${selection[@]}" | edir && tags_clear && cdir '' "$f" ; }

Cheers, Nadim

**Comment by bulletmark** [comment]
Thanks for that. Actually I use `edir` many times per day nowadays. It has become indispensable. If you use the command line I have another tool which I have used for >18 years, possibly 100's of times per day which I find even more useful and that is  [cdhist](https://github.com/bulletmark/cdhist) so you may want to check that out also. I can't see how others can get by without something similar to quickly navigate directories from the command line.

**Comment by nkh** [comment]
Hi, but I have written so many 'cd' wrappers that I have them in a special file for them now. Being 55 and working almost exclusively in terminals in linux has that effect. For exploratory cd I use my file manager to get me where I want. I you are on Linux and use Tmux and Vim, I'll have a first public release, ie it's not just for me anymore, shortly.
