### ISSUE TITLE
Option to preview + confirm changes before they're actually executed?

### ISSUE THREAD

**Issue by hi2u** [bulletmark/edir#19]
Great program!  I really like that it shows colourful messages on what it's doing when you exit your editor.

Is there a way to have it show me these messages on what it will do, but not actually do them until I confirm?  i.e. With a confirmation prompt with y/n to continue or something?

I just get a little paranoid when I'm using these bulk renamer programs, especially considering this one can also delete files too.  

I had a look through the existing args, but couldn't see something that sounded like this.

**Comment by bulletmark** [comment]
I think this was asked for previously but I was reluctant to implement it due to some complications. I can see some people would want though so I will add it when i get back from holidays in one week.

**Comment by bulletmark** [comment]
PS: I have basically got it going ok already but want to test it more thoroughly.

**Comment by bulletmark** [comment]
I've implemented this and made new release 2.22 including it. See the [Previewing Changes](https://github.com/bulletmark/edir#previewing-changes) section I added to describe it.

Thanks for the prompt. I should have added this long ago as it makes sense that people would want it.

**Comment by bulletmark** [comment]
@hi2u I have enhanced this function and released version 2.23. Please read the [updated section in the README](https://github.com/bulletmark/edir#previewing-changes).

**Comment by hi2u** [comment]
Awesome, thanks for adding this @bulletmark !
