### ISSUE TITLE
Suggestion: change the default `.sh` suffix for the temporary file

### ISSUE THREAD

**Issue by denilsonsa** [bulletmark/edir#21]
A default `.sh` suffix was added in f4600c616d39c609da5a1cfecb36f1f301c18bcd:

> `edir` creates the temporary editing file with a `.sh` suffix so
>  your EDITOR may syntax highlight the entries. Optionally, you can
>  change this default suffix.

Unfortunately, this default doesn't give a good experience:

![Screenshot 1 of vim/edir, renaming some music files](https://github.com/bulletmark/edir/assets/121676/2975c32e-60ad-49e7-a1d0-f5d60619ab93)

![Screenshot 2 of vim/edir, renaming some music files](https://github.com/bulletmark/edir/assets/121676/9da448aa-c348-45ac-a7a4-9592d3dcdd68)

![Screenshot 3 of vim/edir, renaming some music files](https://github.com/bulletmark/edir/assets/121676/11719d9a-1e10-49c9-8550-a7c67341d197)

![Screenshot 4 of vim/edir, renaming some music files](https://github.com/bulletmark/edir/assets/121676/19f37a9c-168c-4c65-8953-eac1252e93b7)

For any filename with special characters (and by "special" it can be digits, or anything with a special meaning in shell script), the syntax highlighting is bad. So bad it makes the UX incredibly worse for the user.

May I suggest a default being `.edir` instead? And then you or someone could create a simple syntax file for this type. And I'd argue that an unrecognized filetype with no syntax highlighting is better than a broken highlighting like that one on the screenshots.

**Comment by denilsonsa** [comment]
Like [this syntax highlighting I created](https://github.com/denilsonsa/vim-edir-syntax) based on [another work](https://github.com/ray-pH/vim-edir-syntax).

**Comment by bulletmark** [comment]
*Sorry for the slow response. I am travelling OS with my family atm*.

I think it is far too ambitious to attempt to create a new syntax definition specific to this minor edir tool. Sure you/I could create one for vim but that is only one (now rather obscure) editor among very many others.

You say the present `.sh` choice *doesn't give a good experience* but I disagree. I like that vim basically highlights those file names which i should edit to make them more compatible with the linux shell.

**Comment by bulletmark** [comment]
No reply from OP and given my comment I am not going to change this sorry.
