### ISSUE TITLE
Allow copying files

### ISSUE THREAD

**Issue by NightMachinery** [bulletmark/edir#4]
https://github.com/trapd00r/vidir/issues/8

**Comment by bulletmark** [comment]
For some reason I did not get a notification about this issue?

Can you please at least add 1 sentence when you raise an issue?!

**Comment by bulletmark** [comment]
Commit d95e6b065e78f02108348cdfe561198761bb0d29 for release 2.6 adds copy functionality.

**Comment by NightMachinery** [comment]
Thanks.
