### ISSUE TITLE
[BUG] Renaming a directory and putting files into the new name

### ISSUE THREAD

**Issue by NightMachinery** [bulletmark/edir#7]
```
./dir1/
./a.txt
```
to
```
./dir2/
./dir2/a.txt
```
will cause `dir1` to be renamed to `dir1~`.

**Comment by bulletmark** [comment]
It is too difficult to automatically resolve many complicated combinations like this and there is often not a single unique resolution anyhow so you are better off running `edir` one of more times to rename and/or move files in stages. In short, I am aware of situations like this but I am not planning to add a sophisticated resolver.

**Comment by schlomo** [comment]
I understand the complexities of solving that, do you see a chance to detection for the problem?

For example I edit a long list and do try to make such a change, then it would be nice to get an error and the chance to try again and go fix my edit.

Another thought: Maybe a "complete" solution is too much, but a simple solution could solve already 95% of such use cases: Simply order the actions like this:

1. create new and missing directories
2. rename directories
3. rename files

Wouldn't that solve this for many common use cases?

**Comment by bulletmark** [comment]
No, I started somewhat down the track to try to do this when I first created edir but found too many ambiguous situations where it is impossible to work out definitively what the user intends. Simply don't try to do complicated edits in one pass. Do your edits in stages.

**Comment by NightMachinery** [comment]
@bulletmark I think these set of rules are pretty solid:
- if a director has been renamed, move the files inside that directory into the new directory (which can exist and have some files of its own, or it can be created), and then remove the old directory (if it's now empty)
- move files to their new location, create any missing dirs in the process
- accept the `-i` flag: ask the user interactively if destination files exist whether to proceed with the rename

Of course, these rules aren't perfect, but they're fairly intuitive and better than the current behavior where weirdly named duplicate directories are created.
