### ISSUE TITLE
Can't delete files with spaces in their names using trash-put

### ISSUE THREAD

**Issue by KodyVB** [bulletmark/edir#9]
If you make a file with spaces in its name, i.e. `touch "a test"`, then try to delete it with `edir -t`, it tries to treat it as separate files "a" and "test" with the output:
```
Remove a test ERROR: trash-put error: trash-put: cannot trash non existent 'a'
trash-put: cannot trash non existent 'test'
```

**Comment by bulletmark** [comment]
Fixed this with commit d121a789cfb47e61c2562f47d2678e6a23e182df and released new version [2.9](https://github.com/bulletmark/edir/releases/tag/2.9). Thanks for your bug report.
